[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.4",
    "nest-asyncio>=1.6.0",
    "openai>=1.88.0",
    "openai-agents>=0.0.18",
    "rich>=14.0.0",
]
