[project]
name = "mcp-graphrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphrag>=2.3.0",
    "mcp>=1.9.4",
    "pandas>=2.3.0",
    "pathlib>=1.0.1",
]
