[project]
name = "mcp-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.3.0",
    "httpx>=0.28.1",
    "litellm==1.67.2",
    "pymysql>=1.1.1",
]
